/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jurostela;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Portella
 */
public class JurosTelaJF extends javax.swing.JFrame {

    /**
     * Creates new form JurosTelaJF
     */
    public JurosTelaJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        lbl_result = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRBtn_jc = new javax.swing.JRadioButton();
        jRBtn_js = new javax.swing.JRadioButton();
        jRBtn_vp = new javax.swing.JRadioButton();
        jRBtn_vf = new javax.swing.JRadioButton();
        jRBtn_tempo = new javax.swing.JRadioButton();
        jRBtn_taxa = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_vp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_vf = new javax.swing.JTextField();
        txt_tempo = new javax.swing.JTextField();
        txt_taxa = new javax.swing.JTextField();
        btn_result = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Resultado");

        lbl_result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_result.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(jRBtn_jc);
        jRBtn_jc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBtn_jc.setSelected(true);
        jRBtn_jc.setText("Juros Compostos");
        jRBtn_jc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRBtn_jc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn_jcActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBtn_js);
        jRBtn_js.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBtn_js.setText("Juros Simples");
        jRBtn_js.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn_jsActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRBtn_vp);
        jRBtn_vp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBtn_vp.setText("Valor Presente");
        jRBtn_vp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn_vpActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRBtn_vf);
        jRBtn_vf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBtn_vf.setText("Valor Futuro");
        jRBtn_vf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn_vfActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRBtn_tempo);
        jRBtn_tempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBtn_tempo.setText("Tempo");
        jRBtn_tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn_tempoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRBtn_taxa);
        jRBtn_taxa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBtn_taxa.setText("Taxa");
        jRBtn_taxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn_taxaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SELECIONE O TIPO DO CÁLCULO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBtn_jc)
                            .addComponent(jRBtn_js))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBtn_taxa)
                            .addComponent(jRBtn_tempo)
                            .addComponent(jRBtn_vp)
                            .addComponent(jRBtn_vf))
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBtn_jc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBtn_js))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBtn_vp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBtn_vf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBtn_tempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBtn_taxa)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CALCULADORA FINANCEIRA");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Valore Presente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Valor Futuro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tempo");

        txt_vp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_vp.setText("0");
        txt_vp.setEnabled(false);
        txt_vp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Taxa");

        txt_vf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_vf.setText("0");
        txt_vf.setEnabled(false);

        txt_tempo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tempo.setText("0");
        txt_tempo.setEnabled(false);

        txt_taxa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_taxa.setText("0");
        txt_taxa.setEnabled(false);

        btn_result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_result.setText("CALCULAR");
        btn_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INSIRA OS VALORES PARA O CÁLCULO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_vp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_taxa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tempo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_vf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_result, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_vp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_vf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btn_result, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_taxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_result, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 159, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_result))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Calculo_Juros CalculoObj;
    int tipo = 0;

    private void btn_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultActionPerformed
        // TODO add your handling code here:

        if (txt_vp.getText().isEmpty() | txt_vf.getText().isEmpty()
                | txt_taxa.getText().isEmpty() | txt_tempo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos não podem estar vazios");
        } else {

            CalculoObj = new Calculo_Juros();
//        CalculoObj.vrpres = Double.parseDouble(txt_vp.getText());
            CalculoObj.setVrpres(Double.parseDouble((txt_vp.getText()).replaceAll(",", ".")));
            CalculoObj.setVrfut(Double.parseDouble((txt_vf.getText()).replaceAll(",", ".")));
            CalculoObj.setTaxa(Double.parseDouble((txt_taxa.getText()).replaceAll(",", ".")));
            CalculoObj.setTempo(Integer.parseInt((txt_tempo.getText()).replaceAll(",", ".")));

            /*CalculoObj.vrfut = Double.parseDouble((txt_vf.getText()).replaceAll(",", "."));
        CalculoObj.taxa = Double.parseDouble(txt_taxa.getText());
        CalculoObj.tempo = Integer.parseInt(txt_tempo.getText());*/
            if (jRBtn_jc.isSelected()) {
                tipo = 1;
            } else {
                tipo = 2;
            }

            if (jRBtn_vp.isSelected()) {
                CalculoObj.Calcvp(tipo);
            } else if (jRBtn_vf.isSelected()) {
                CalculoObj.Calcvf(tipo);
            } else if (jRBtn_taxa.isSelected()) {
                CalculoObj.CalcTaxa(tipo);
            } else {
                CalculoObj.CalcTempo(tipo);
            }

            lbl_result.setText(String.format("%.2f", CalculoObj.resultado));

        }
    }//GEN-LAST:event_btn_resultActionPerformed

    private void jRBtn_jsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn_jsActionPerformed
        // TODO add your handling code here:
/*        if (jRBtn_js.isSelected()) {
            //  JOptionPane.showMessageDialog(rootPane, "teste de clique");
            jRBtn_vf.setEnabled(true);
            jRBtn_vp.setEnabled(true);
            jRBtn_taxa.setEnabled(true);
            jRBtn_tempo.setEnabled(true);
        }*/
    }//GEN-LAST:event_jRBtn_jsActionPerformed

    private void jRBtn_jcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn_jcActionPerformed
        // TODO add your handling code here:
/*        if (jRBtn_jc.isSelected()) {
            //  JOptionPane.showMessageDialog(rootPane, "teste de clique");
            jRBtn_vf.setEnabled(true);
            jRBtn_vp.setEnabled(true);
            jRBtn_taxa.setEnabled(true);
            jRBtn_tempo.setEnabled(true);
        }*/
    }//GEN-LAST:event_jRBtn_jcActionPerformed

    private void jRBtn_vpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn_vpActionPerformed
        // TODO add your handling code here:
        if (jRBtn_vp.isSelected()) {

            txt_vp.setEnabled(false);
            txt_vp.setText("0");

            txt_vf.setEnabled(true);
            txt_vf.setText("0");
//            CalculoObj.setVrfut(0);

            txt_taxa.setEnabled(true);
            txt_taxa.setText("0");
//            CalculoObj.setTaxa(0);

            txt_tempo.setEnabled(true);
            txt_tempo.setText("0");
//            CalculoObj.setTempo(0);

        }
    }//GEN-LAST:event_jRBtn_vpActionPerformed

    private void jRBtn_taxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn_taxaActionPerformed
        // TODO add your handling code here:
        if (jRBtn_taxa.isSelected()) {
            txt_vp.setEnabled(true);
            txt_vp.setText("0");

            txt_vf.setEnabled(true);
            txt_vf.setText("0");
//            CalculoObj.setVrfut(0);

            txt_taxa.setEnabled(false);
            txt_taxa.setText("0");

//            CalculoObj.setTaxa(0);
            txt_tempo.setEnabled(true);
            txt_tempo.setText("0");
//            CalculoObj.setTempo(0);
        }
    }//GEN-LAST:event_jRBtn_taxaActionPerformed

    private void jRBtn_vfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn_vfActionPerformed
        // TODO add your handling code here:
        if (jRBtn_vf.isSelected()) {
            txt_vp.setEnabled(true);
            txt_vp.setText("0");

            txt_vf.setEnabled(false);
            txt_vf.setText("0");

//            CalculoObj.setVrfut(0);
            txt_taxa.setEnabled(true);
            txt_taxa.setText("0");
//            CalculoObj.setTaxa(0);

            txt_tempo.setEnabled(true);
            txt_tempo.setText("0");
//            CalculoObj.setTempo(0);
        }
    }//GEN-LAST:event_jRBtn_vfActionPerformed

    private void jRBtn_tempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn_tempoActionPerformed
        // TODO add your handling code here:
        if (jRBtn_tempo.isSelected()) {
            txt_vp.setEnabled(true);
            txt_vp.setText("0");

            txt_vf.setEnabled(true);
            txt_vf.setText("0");
//            CalculoObj.setVrfut(0);

            txt_taxa.setEnabled(true);
            txt_taxa.setText("0");
//            CalculoObj.setTaxa(0);

            txt_tempo.setEnabled(false);
            txt_tempo.setText("0");
//            CalculoObj.setTempo(0);
        }
    }//GEN-LAST:event_jRBtn_tempoActionPerformed

    private void txt_vpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JurosTelaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JurosTelaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JurosTelaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JurosTelaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JurosTelaJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_result;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBtn_jc;
    private javax.swing.JRadioButton jRBtn_js;
    private javax.swing.JRadioButton jRBtn_taxa;
    private javax.swing.JRadioButton jRBtn_tempo;
    private javax.swing.JRadioButton jRBtn_vf;
    private javax.swing.JRadioButton jRBtn_vp;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JTextField txt_taxa;
    private javax.swing.JTextField txt_tempo;
    private javax.swing.JTextField txt_vf;
    private javax.swing.JTextField txt_vp;
    // End of variables declaration//GEN-END:variables
}
